name: bump-my-casks
on:
  schedule:
    - cron: 0 4,16 * * *
  workflow_dispatch:

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{ secrets.BUMP_CASK_TOKEN }}
        tap: jimscard/homebrew-ollama
        cask: ollama, ollama-model-updater
        livecheck: true
        dryrun: false